### ISSUE TITLE
Dashboard is non functional

### ISSUE THREAD

**Issue by sria91** [dcaputo-harmoni/open-balena-admin#11]
I've tried setting-up `open-balena-admin` on my local machine using both docker-compose and kubernetes.
But I encounter the same error: "Non-functional dashboard".

It looks like some communication issue between `open-balena-postgrest` and `open-balena-db` from browser console error messages.

Following are the screenshots of the chrome devtools window and dashboard for your reference:
![open-balena-admin-error-chrome-devtools](https://user-images.githubusercontent.com/3253247/172393331-3426069e-ed1f-4083-88d9-753e65bddc0f.png)
![open-balena-admin-error-users-page](https://user-images.githubusercontent.com/3253247/172393350-8e464886-1191-40dc-8f18-b3e2c7b317e9.png)

Logs from `open-balena-postgrest`:
```
07/Jun/2022:15:24:37 +0000: An error ocurred when trying to query database settings for the config parameters
07/Jun/2022:15:24:37 +0000: ConnectionError (Just "could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n")
07/Jun/2022:15:24:37 +0000: Attempting to connect to the database...
07/Jun/2022:15:24:37 +0000: {"details":"could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n","code":"","message":"Database connection error. Retrying the connection."}
07/Jun/2022:15:24:37 +0000: Attempting to reconnect to the database in 0 seconds...
> postgrest-proxy@1.0.0 start
> node postgrest-proxy.js
[HPM] Proxy created: / -> http://127.0.0.1:3000
07/Jun/2022:15:24:38 +0000: {"details":"could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n","code":"","message":"Database connection error. Retrying the connection."}
07/Jun/2022:15:24:38 +0000: Attempting to reconnect to the database in 1 seconds...
07/Jun/2022:15:24:40 +0000: {"details":"could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n","code":"","message":"Database connection error. Retrying the connection."}
07/Jun/2022:15:24:40 +0000: Attempting to reconnect to the database in 2 seconds...
07/Jun/2022:15:24:44 +0000: {"details":"could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n","code":"","message":"Database connection error. Retrying the connection."}
07/Jun/2022:15:24:44 +0000: Attempting to reconnect to the database in 4 seconds...
[HPM] Error occurred while proxying request postgrest.openbalena.abc/user?limit=10&offset=0&order=id.asc to http://127.0.0.1:3000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
07/Jun/2022:15:24:52 +0000: {"details":"could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n","code":"","message":"Database connection error. Retrying the connection."}
07/Jun/2022:15:24:52 +0000: Attempting to reconnect to the database in 8 seconds...
[HPM] Error occurred while proxying request postgrest.openbalena.abc/user?limit=10&offset=0&order=id.asc to http://127.0.0.1:3000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
07/Jun/2022:15:25:08 +0000: {"details":"could not translate host name \"openbalena-db.openbalena\" to address: Name does not resolve\n","code":"","message":"Database connection error. Retrying the connection."}
07/Jun/2022:15:25:08 +0000: Attempting to reconnect to the database in 16 seconds...
```

Logs from `open-balena-db`:
```
2022-06-07 14:49:50.879 UTC [6442] LOG: invalid length of startup packet
...
2022-06-07 15:16:56.159 UTC [6776] LOG: invalid length of startup packet
```

@dcaputo-harmoni Can you please help me resolve this issue?

**Comment by dcaputo-harmoni** [comment]
This looks like a docker networking issue - can you ssh into the open-balena-postgrest container and run `ping openbalena-db`?  I suspect it will not resolve, in which case you need to confirm that the `open-balena-admin` containers are running within the same docker network as `open-balena`. 

You might want to take a look at the [services.yaml](https://github.com/dcaputo-harmoni/open-balena-admin/blob/main/compose/services.yml) file, which you'll see puts all of the `open-balena-admin` containers on the `openbalena_default` network, which is the default network used by `open-balena`.  If you have changed this, or if you are running your `open-balena` on a different docker server than `open-balena-admin`, you'll need to somehow ensure that the `open-balena-admin` containers can communicate with the `open-balena` containers.

**Comment by sria91** [comment]
Thanks for the reply @dcaputo-harmoni. Sorry for the confusion. Your point might be helpful in case I'm running them using docker. But I'm running both open-balena and open-balena-admin using kubernetes, where both of them are running on the same `default` namespace. Am I missing any other configuration to get it to work?

**Comment by dcaputo-harmoni** [comment]
This looks like a namespace issue.  Notice the error message is looking for `openbalena-db.openbalena` but you are using `openbalena-db.default`. You will either need to change the service config files to point to the default namespace (change references to `openbalena-db.default`) or put openbalena in the `openbalena` namespace. 

By the way - nice work getting all this up and running in kubernetes.
