### ISSUE TITLE
VNC Not able to dispaly at full screen.

### ISSUE THREAD

**Issue by jcklerk** [dcaputo-harmoni/open-balena-admin#21]
when I connect to a client using VNC i can not put VNC in to Fullscreen mode.
and get the following error

```
TypeError: Disallowed by permissions policy
    at HTMLInputElement.toggleFullscreen (https://remote.openbalena.example.nl/novnc/app/ui.js:1277:42
```

can you fix this in the open-balena-ui and open-balena-remote ?

**Comment by dcaputo-harmoni** [comment]
This has been fixed in the latest version of open-balena-admin, which now has a fullscreen toggle on the connect modal.
