### ISSUE TITLE
About SSH

### ISSUE THREAD

**Issue by ArrayIndexOutOfBound** [dcaputo-harmoni/open-balena-admin#3]
Hello,

First of all, thanks for this project, it sems to be very usefull for me, but even for futur people who will find this little gem.
Anyways, if I am here to report an issue, it's because it seems that I'm not able to connect via SSH to my device.

The error itself : 
![image](https://user-images.githubusercontent.com/81418700/160552991-526511cc-a695-46d3-abe0-6d9105346b9d.png)

After searching a bit in the files of `openbalena`, and the files if this project, I found this :
The content of `openbalena/config/activate`

![image](https://user-images.githubusercontent.com/81418700/160553210-d22215a1-cd7b-450f-81e3-2b5f2ae02552.png)

I guess that this specific line shouldn't be empty ?
If I'm trying to do a ssh connection via the `balena-cli`, it asks for the password of `admin@ssh.devices.mydomain.notlocal`, which I do not remember setting up anywhere.

Thanks for giving me a bit of your time, have a good day.

**Comment by dcaputo-harmoni** [comment]
@ArrayIndexOutOfBound thank you for trying it out! Could you provide some additional details on your setup?  Also, are your devices running in development or production mode?  If you are not able to ssh into a device locally using `balena-cli`, or if you are not able to establish a tunnel to a device using `balena tunnel`, connect won't work.  As currently implemented, connect relies on `balena tunnel` to establish a connection, and assumes the device is in development mode - i.e. that it is accessible using root login (no password) on port 22222.  We would need to implement some additional logic to pass SSH keys and/or passwords to `open-balena-remote` for this to work on production mode devices.

**Comment by ArrayIndexOutOfBound** [comment]
Hello again !

Yep, I do think that I am using the production image instead of the development one, I will change that if needed (I think it's necessary after reading the point about allowing root login).
I guess that explain why I needed to manually add the ssh-keys in the `config.json` on the boot partition
About the tunnel, I don't know how to mount one, sorry.

Here is a little diagram of how my devices are installed :
![Schema](https://user-images.githubusercontent.com/81418700/160641879-3afbce8d-7d28-4bb2-89b8-2bdb0a1de49b.png)

As you might have already guessed, english isn't my primary language, sorry if there is some spelling / grammatical errors.

Thanks for your time !

**Comment by dcaputo-harmoni** [comment]
@ArrayIndexOutOfBound your setup looks fine to me - other than changing to development mode (which hopefully won't be required once we implement the ability to utilize SSH keys) I don't see any issues.  What happens if you try running the command from your local computer: `balena tunnel <uuid> -p 22222`?  And if that is successful, try running `ssh root@localhost -p 22222`.  In essence, that is all that remote is doing.

**Comment by ArrayIndexOutOfBound** [comment]
Hello,
I tried doing the tunnel and then using the ssh : here are the results :
Creating the tunnel (on the server):
![image](https://user-images.githubusercontent.com/81418700/160769397-c978aa18-2b9b-4b0c-bb3f-95e4903b25b7.png)
Trying to SSH localhost (on the server):
![image](https://user-images.githubusercontent.com/81418700/160769465-ce87dc3f-b1f1-40f2-99a4-4ee2c63d88e6.png)
Trying to SSH via the local computer :
![image](https://user-images.githubusercontent.com/81418700/160769539-6a200a62-b44e-4487-be08-97555c1ec061.png)
Here is what the dashboard is telling me :
![image](https://user-images.githubusercontent.com/81418700/160769691-585883d5-8490-43f7-bd56-a97490ed1f8f.png)

It seems that the OS is still on "prod" mode ? But I did this when downloading a second time the os :
![image](https://user-images.githubusercontent.com/81418700/160769878-2d22a63b-2d75-4bc5-95a8-22f537414b70.png)

BalenaPi4_DEV.img being the image downloaded directly on the [balena](https://www.balena.io/os/) page, unziped

I will update this post I find something.

**Comment by ArrayIndexOutOfBound** [comment]
Hello again !

I managed to add `"developmentMode": true` to the config.json, and now the OS on the web page :
![image](https://user-images.githubusercontent.com/81418700/160777799-f0a530fd-af67-4fee-b32c-9ae25872240b.png)

I still am getting the "Error" when trying to SSH via the `open-balena-ui`, but when creating the tunnel by hand, it seems to be working well.

![image](https://user-images.githubusercontent.com/81418700/160778106-81135cec-2951-43c0-b1ad-eeaf5e80b478.png)
![image](https://user-images.githubusercontent.com/81418700/160778213-70d95e61-6783-4cbe-b6a8-2933379507d6.png)

**Comment by dcaputo-harmoni** [comment]
@ArrayIndexOutOfBound sounds like we are getting closer. Could you confirm the URL that is being passed to `open-balena-remote` is properly formed?  You can get the URL by right clicking the iframe that connect is running in and inspecting the details. And then can you try running that same URL in a new browser window?  I am wondering if this is a `CORS` issue, and we need to relax your browser settings.

**Comment by ArrayIndexOutOfBound** [comment]
The link in the iframe is something like this:
http://remote.domain.notlocal:8000/?service=ssh&uuid=string&jwt=superlongstring

I tried some ports : 
- 8080 : works fine, I have acess to the UI
- 10000-10009 : gives me the "error" page
- 8000 : seems to be broken, here is the message that is printed
![image](https://user-images.githubusercontent.com/81418700/160833353-4b1a64be-2f04-41e5-853d-49b7f8d0f666.png)

**Comment by dcaputo-harmoni** [comment]
OK - a couple of things from your response.  I'm not sure why the iframe URL would be referencing port 8000, it should be 10000.  Can you try pasting that same URL into a new browser window and change port 8000 to 10000?

If you take a look in the `services.yaml` file that builds `open-balena-admin` you will see the following line:

`
REACT_APP_OPEN_BALENA_REMOTE_URL: http://remote.${OPENBALENA_HOST_NAME}:10000
`

This is the same environment variable that is used to generate the URL to call connect (see below from `src/ui/DeviceConnect.js` in the `open-balena-ui` container:

`
let REMOTE_HOST = process.env.REACT_APP_OPEN_BALENA_REMOTE_URL;
            let session = authProvider.getSession();
            let containerChoices = [{id: 0, name: 'host'}];
            let containerServices = [[{id: 0, name: 'SSH'}]];
            let containerLinks = [[`${REMOTE_HOST}?service=ssh&uuid=${props.record.uuid}&jwt=${session.jwt}`]];
`

I can't think of a reason why your instance would be trying to call port 8000 - I'm assuming you did not modify `services.yaml`?

**Comment by ArrayIndexOutOfBound** [comment]
SORRY !
I meant -->
http://remote.domain.notlocal:10000/?service=ssh&uuid=string&jwt=superlongstring
Not -->
http://remote.domain.notlocal:8000/?service=ssh&uuid=string&jwt=superlongstring
As I typed this by hand, and at the same time testing the opened ports, I wrote something wrong.

I did not touch the `service.yml` file, knowing well that I would break something.
![image](https://user-images.githubusercontent.com/81418700/160838244-12100288-2160-4b2c-8c98-9a24e988de2a.png)

**Comment by dcaputo-harmoni** [comment]
OK, that makes more sense.  So the issue seems to be isolated to the `open-balena-remote` container.  Do you have SSH access to this container?  if so, can you ssh into that container, kill the active `node` process (which you can find using `ps -A`, modify `open-balena-remote.js` to change the following line:

```
const DEBUG = false;
```

to:

```
const DEBUG = true;
```

Then run `node open-balena-remote.js`, and try to access remote either via the admin user interface or directly from the browser window, and send the debug info you see in the console (sanitized as you see fit) -- thanks.

**Comment by ArrayIndexOutOfBound** [comment]
Alright !

As I can understand, I have a problem with a `self signed certificate`
![image](https://user-images.githubusercontent.com/81418700/160842850-d122ce90-23da-4b2e-99aa-0e3c82a65056.png)

I don't know how certificates works, but does it have to do with the fact that when I'm trying to acess the webpage (admin or api), I sometimes get a warning about the fact that the website is 'dangerous ?'

When doing `history` on the server, I was able to retrieve the following quickstart of `openbalena`
> bash quickstart -U supersecret@admin.something -P ultrasecret -d domain.notlocal -p

And for openbalena-admin

> bash quickstart -j longstring -v 0.139.0 -d same.domain

**Comment by dcaputo-harmoni** [comment]
OK, looks like you found the issue.  It appears your `open-balena` server is using a self-signed certificate, and `balena-cli` does not like self signed certificates.  I'm surprised your local `balena-cli` instance is not complaining in the same way - have you made any accommodations on your local machine to address this in the past?

One solution you can try is modifying the following code in `open-balena-remote.js` and restarting it:

```
          sessionData.tunnel.pid = await executeCommand(tunnelCmd, {
            uuid: req.query.uuid, 
            remotePort: remotePort,
            localPort: sessionData.tunnel.port,
            tunnelID: sessionData.tunnel.id
            }, {BALENARC_DATA_DIRECTORY: sessionData.sessionDir}, true);
```

to this:

```
          sessionData.tunnel.pid = await executeCommand(tunnelCmd, {
            uuid: req.query.uuid, 
            remotePort: remotePort,
            localPort: sessionData.tunnel.port,
            tunnelID: sessionData.tunnel.id
            }, {BALENARC_DATA_DIRECTORY: sessionData.sessionDir, NODE_TLS_REJECT_UNAUTHORIZED: 0}, true);
```

I suspect this would fix your issue, but it's really more of a workaround and I'm not sure we would want that in the main branch of `open-balena-remote` as it could create security issues for others who utilize valid certificates.  I have a broader plan to replace `balena tunnel` with a custom https proxy tunnel solution, but it's lower on the list as balena really struggles with self signed certificates generally and I suspect you will run into other issues with balena.

**Comment by ArrayIndexOutOfBound** [comment]
I have tried modifying the `open-balena-remote-js`, the previous error has dissapeared, but it seems to be once again, blocked by the fact that the certificates are not valid.
![image](https://user-images.githubusercontent.com/81418700/160991386-fbe14a07-18fc-4cd4-86d4-a447058ddd4c.png)

I will try to search on how to make the certificates "approuved" by my/any web browser.
It cannot be 'that' complicated, right ...?

As for why my balena-cli on the server seems to be ok, it's because I followed the insctruction on [the getting started page](https://www.balena.io/open/docs/getting-started/) on my .profile and .bashrc so it get set on reboot.
`export NODE_EXTRA_CA_CERTS='/path/to/ca.crt'`

**Comment by ArrayIndexOutOfBound** [comment]
Update :
I did a fresh install of open-balena, but this time, with the `-c` parameter, which created good certificates (since now, neither my web browser nor balena-cli is complaining about self signed certificates).

Here are the logs of `open-balena-remote.js`, with `DEBUG` set to `true` :
![image](https://user-images.githubusercontent.com/81418700/161012757-69ff2c56-303f-4b65-8b9b-923647d25a07.png)

I can confirm that locally, the Raspberry is responding to the SSH connection, on port 22222
![image](https://user-images.githubusercontent.com/81418700/161013336-67468463-e21e-4e93-aa75-daf196387ae0.png)

**Comment by ArrayIndexOutOfBound** [comment]
Copying the URL to another window doesn't work.
With HTTP, I get the classic ERROR page.
With HTTPS, it seems to not be supported since I'm getting an ERR_SSL_PROTOCOL_ERROR page.

I think I need to change some parameters ? Since it works when inside the docker container, it seems to be working well.
Or maybe check the proxy at port 10000, since the error seems to be coming from that "no valid session"

It's very close to working accordingly, at least some people maight find this Issue quite helping.

**Comment by dcaputo-harmoni** [comment]
@ArrayIndexOutOfBound can you confirm what browser you are using?  `open-balena-remote` uses localStorage to store the session ID, and it seems that it can’t find your session from the logs. Here is the compatibility chart for localStorage:

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

also, can you confirm if you are seeing any errors in the browser console?

**Comment by ArrayIndexOutOfBound** [comment]
I am using Google Chrome, and is up to date.
I will install Mozilla and post this in a few minutes.
Mozilla is more talkative than Chrome : I am getting a cookie error I think ?
![image](https://user-images.githubusercontent.com/81418700/161057064-f5bdc33f-63d1-46c2-a70a-17408f9a7bcd.png)
I don't know how they work, but as I undertsand it, it's discarded since it's not considered as `"secure"` ?

**Comment by dcaputo-harmoni** [comment]
Ok, further progress. That’s clearly the issue you are having now - without the cookie proxy can’t work. Can you try going to "chrome://flags" and disabling "Cookies without SameSite must be secure"?

**Comment by ArrayIndexOutOfBound** [comment]
I tried by having these two rules at `disabled` and then `enabled`
![image](https://user-images.githubusercontent.com/81418700/161062889-b01c164d-5f50-4a73-9e8a-68e4b2592833.png)

I am currently searching for equivalent settings on FireFox

**Comment by dcaputo-harmoni** [comment]
Not sure if it is a translation thing but those don’t look like the right settings. Here is another article that describes which settings to change:

https://www.chromium.org/updates/same-site/test-debug/

**Comment by ArrayIndexOutOfBound** [comment]
According to the documentation, since my Chrome is version 100 and it's said that :
> NOTE: These flags were removed in Chrome 91, as the behavior is enabled by default as of Chrome 85. If you are running Chrome 91 or newer, you can skip to step 3.

I have nothing to do with theses flags that seem to be Enabled by default now.

If I translate the error message, we get something like 
> You can't define the "remote.10000" cookie to `secure` if you are not using HTTPS

Do I need to remove the` secure` somewhere, or maybe check on how to setup certificates for your docker images ?

**Comment by ArrayIndexOutOfBound** [comment]
Alright ! 
By setting the cookie to false [here](https://github.com/dcaputo-harmoni/open-balena-remote/blob/8c5490c083a66474b21d84f0ffe7fdd661a4bef6/open-balena-remote.js#L61) and exclusively with Mozilla for now, it works !
![image](https://user-images.githubusercontent.com/81418700/161073932-536af619-eaa6-48f1-a633-3460238dbb6b.png)
I won't yet close this issue, because I will try to make it work over HTTPS and with the cookie set to `secure` AND on Google Chrome.
In the meantime, thanks a lot for your time, I learned things during this couple of days !

**Comment by dcaputo-harmoni** [comment]
Great! And just to confirm, when you say that you set the cookie to false do you mean you set "httpOnly" to false, or "secure" to false? (or both?)  It seems this issue is related to http connections; remote is running fine on my https server otherwise.  If this is the case, I can work in a parameter into the quickstart script to specify if the servers will be running via http or https, and if https, it will set all URLs to https and also set secure to true, otherwise all will be http and secure will be false.

**Comment by ArrayIndexOutOfBound** [comment]
I changed only "secure" to `false` to make it work on Firefox, I still am searching on why Chrome seems to be reluctant about the cookie.
I think that being able to to choose between http and https is a good idea on your script !
But does that mean that we will need to change some of the `openbalena cert-provider` configs to generate some certificates for your dockers ?

**Comment by dcaputo-harmoni** [comment]
Added insecure mode option at build time `quickstart -i` which sets secure mode to false in remote container.

**Comment by anthonyra** [comment]
> Added insecure mode option at build time `quickstart -i` which sets secure mode to false in remote container.

```
./scripts/quickstart -j $OPENBALENA_JWT_SECRET -v $OPENBALENA_API_VERSION_TAG -d $OPENBALENA_HOST_NAME -i
Invalid argument: -i
usage: ./scripts/quickstart [-h] [-d DOMAIN] [-U USERNAME] [-P PASSWORD] [-p PORT] -v VERSION -j JWT_SECRET
```

**Comment by shawaj** [comment]
@dcaputo-harmoni is this solved now re SSH with keys in production?

Based on this post? https://forums.balena.io/t/production-image-ssh-access/355781
