### ISSUE TITLE
docker-compose: command not found

### ISSUE THREAD

**Issue by djohnson-mulytic** [dcaputo-harmoni/open-balena-admin#39]
Hi
I'm probably doing something silly here, but I cannot get the compose up to work
Below is the command and the output I get
~/open-balena/open-balena-admin/scripts$ ./compose up
./compose: line 26: docker-compose: command not found

I tried to add 'which docker' but that didn't help. Any thoughts where I am going wrong?

**Comment by robbe-haesendonck** [comment]
Hello!

It's probably because you've installed a newer version of docker-compose. Try replacing the instances of `docker-compose` with `docker compose`.

For your reference: https://docs.docker.com/compose/migrate/

**Comment by djohnson-mulytic** [comment]
Thanks Robbe! It got through most of the setup, since the next one is a different error, Ill open a new ticket. Thanks again!
