### ISSUE TITLE
Docker Images

### ISSUE THREAD

**Issue by ArrayIndexOutOfBound** [dcaputo-harmoni/open-balena-admin#4]
Hello, it's me again !
Opening a new ticket since it's about another mather : docker images.
As I can see in [this](https://github.com/dcaputo-harmoni/open-balena-admin/blob/main/assets/screenshots/device_dashboard_1.png) image, you are able to have multiple images with custom names on your device.
May I know what command do you type when pushing an image ? Everytime I'm trying to deploy something, it's named `main` with some generated string after that.
Thanks again for your time !

**Comment by dcaputo-harmoni** [comment]
The open-balena-admin project is a compilation of three projects - you can find links to their separate github projects on the main page.  The instructions on how to configure multiple images are included on the github page for the open-balena-ui project: https://github.com/dcaputo-harmoni/open-balena-ui

**Comment by ArrayIndexOutOfBound** [comment]
I will check those links.
My questions were more like :
"How could you have multiple container?" --> I will need to check the multicontainer of balena's website as I understood
"How could have customly named you container?" --> you containers are named `app-something`, while when I'm pushing a simple `hello-world`, I don't get to name anything and it automatically called `main`
![image](https://user-images.githubusercontent.com/81418700/161547545-a40e178e-f1b5-4d48-8384-a906798f7469.png)
I'm doing the command `balena deploy Pi4Fleet --emulated`, inside the source directory, where the Dockerfile exist, to get this result.

**Comment by dcaputo-harmoni** [comment]
This sounds like a generic balena question which is not specific to open-balena-admin, so would suggest that you check out the multicontainer link from the earlier note and try building your multicontainer app using docker-compose.
